postdata={
#品牌
'brand':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:11
body.jyType:
body.jyIcon:[CODE]
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:
body.jyGroupId:
body.jyDisplacement:请选择
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',
#车型品牌
'chexingbrand':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:20
body.jyType:
body.jyIcon:
body.jyBrandName:[BRANDNAME]
body.jyBrandId:[BRANDID]
body.jyFamilyId:
body.jyGroupId:
body.jyDisplacement:请选择
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',
#车款
'chekuan':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:21
body.jyType:
body.jyIcon:
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:[FAMILYID]
body.jyGroupId:
body.jyDisplacement:请选择
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',

#车款图片
'chekuanpic':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:60
body.jyType:
body.jyIcon:
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:
body.jyGroupId:[GROUPID]
body.jyDisplacement:请选择
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',

#排气量
'paiqiliang':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:30
body.jyType:
body.jyIcon:
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:
body.jyGroupId:[GROUPID]
body.jyDisplacement:请选择
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',

#手动/自动
'shoudong':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:40
body.jyType:
body.jyIcon:
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:
body.jyGroupId:[GROUPID]
body.jyDisplacement:[ENGINEDESC]
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',

#配置型号
'peizhixinghao':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:50
body.jyType:
body.jyIcon:
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:
body.jyGroupId:[GROUPID]
body.jyDisplacement:
body.jyGearbox:
body.jyParentId:
body.jyFgwCode:请选择
body.comCode:41010088\
''',

#型号
'xinghao':'''\
areaCode:41000000
cityCode:41010000
comCode:41010088
jyImportFlag:1
head.requestType:01
head.requestCode:
head.checkStr:
head.channelNo:
body.jyFlag:81
body.jyType:
body.jyIcon:
body.jyBrandName:
body.jyBrandId:
body.jyFamilyId:
body.jyGroupId:
body.jyDisplacement:
body.jyGearbox:
body.jyParentId:[PARENTID]
body.jyFgwCode:请选择
body.comCode:41010088\
'''

}